filters:
  - kind: Pod
    apiVersion: v1
#    namespaces:
#      include:
#        - surf-screenshotter-dev
#      ignore:
#        - heptio-sonobuoy
    conditions:
      - status.containerStatuses[*].state.terminated.exitCode != 0
    message:
      template: "{NAME} in {NAMESPACE} terminated with nonzero exit code"
      attributes:
        NAME: metadata.name
        NAMESPACE: metadata.namespace

  - kind: Pod
    apiVersion: v1
    conditions:
      - status.containerStatuses[*].restartCount > 10
    message:
      template: "{NAME} in {NAMESPACE} has restarted {RESTART_COUNT} times"
      attributes:
        NAME: metadata.name
        NAMESPACE: metadata.namespace
        RESTART_COUNT: status.containerStatuses[*].restartCount

#handlers:
#  slack:
#    channel: "${SLACK_HANDLER_CHANNEL}"
#    token: $SLACK_HANDLER_TOKEN
#  smtp:
#    from: $SMTP_HANDLER_FROM
#    password: $SMTP_HANDLER_PASSWORD
#    host: smtp.gmail.com
#    port: 587
#    tls: true
#    to:
#      - $SMTP_HANDLER_TO
