filters:
  - kind: Pod
    apiVersion: v1
#    namespaces:
#      include:
#        - surf-screenshotter-dev
#      ignore:
#        - heptio-sonobuoy
    trigger:
      - status.containerStatuses[*].state.terminated.exitCode != 0
    message:
      template: "{NAME} in {NAMESPACE} terminated with nonzero exit code"
      attributes:
        NAME: metadata.name
        NAMESPACE: metadata.namespace
# TODO: Being able to specify which handler should be invoked makes sense if one team manages one namespace and another manages another
#    handlers:
#      - slack

# TODO: Grater than and less than triggers aren't implemented yet so this doesn't work
#  - kind: Pod
#    apiVersion: v1
#    trigger:
#      - status.containerStatuses[*].state.restartCount > 10
#    message:
#      template: "{NAME} in {NAMESPACE} has restarted {RESTART_COUNT}"
#      attributes:
#        NAME: metadata.name
#        NAMESPACE: metadata.namespace
#        RESTART_COUNT: status.containerStatuses[*].state.restartCount

handlers:
  slack:
    channel: "${SLACK_HANDLER_CHANNEL}"
    token: $SLACK_HANDLER_TOKEN
  smtp:
    from: $SMTP_HANDLER_FROM
    password: $SMTP_HANDLER_PASSWORD
    host: smtp.gmail.com
    port: 587
    tls: true
    to:
      - $SMTP_HANDLER_TO
