filters:
  - kind: Pod
    apiVersion: v1
#    namespaces:
#      include:
#        - surf-screenshotter-dev
#      ignore:
#        - heptio-sonobuoy
    conditions:
      - status.containerStatuses[*].state.terminated.exitCode != 0
    message:
      template: "Pod: {NAME} in {NAMESPACE} terminated with nonzero exit code"
      attributes:
        NAME: metadata.name
        NAMESPACE: metadata.namespace

  - kind: Pod
    apiVersion: v1
    conditions:
      - status.containerStatuses[*].restartCount > 10
    message:
      template: "Pod: {NAME} in {NAMESPACE} has restarted {RESTART_COUNT} times"
      attributes:
        NAME: metadata.name
        NAMESPACE: metadata.namespace
        RESTART_COUNT: status.containerStatuses[*].restartCount

  - kind: Event
    apiVersion: v1
    conditions:
      - type == Warning
#      - reason != ImageGCFailed
#      - reason != FreeDiskSpaceFailed
    message:
      template: "Event: Warning {NAME} in {NAMESPACE} (reason: {REASON}, message: {MESSAGE})"
      attributes:
        NAME: metadata.name
        NAMESPACE: metadata.namespace
        REASON: reason
        MESSAGE: message

  - kind: Job
    apiVersion: batch/v1
    conditions:
      - status.conditions[*].type == Failed
    message:
      template: "Job: {NAME} in {NAMESPACE} failed (reason: {REASON}, message: {MESSAGE})"
      attributes:
        NAME: metadata.name
        NAMESPACE: metadata.namespace
        REASON: status.conditions[*].reason
        MESSAGE: status.conditions[*].message

handlers:
  slack:
    channel: "${SLACK_HANDLER_CHANNEL}"
    token: $SLACK_HANDLER_TOKEN
    username: KubeWatcher-dev
    icon: https://github.com/tonsV2/kubewatcher/raw/master/icons/icon.png
  smtp:
    from: $SMTP_HANDLER_FROM
    password: $SMTP_HANDLER_PASSWORD
    host: smtp.gmail.com
    port: 587
    tls: true
    to:
      - $SMTP_HANDLER_TO

settings:
  dryRun: false
  debug: false
