version: '3.6'
services:
  app:
    image: tons/kubewatcher:dev
    build: .
    volumes:
      - ~/.kube/config:/kube/config
      - ./config.yaml:/app/config.yaml
    environment:
      KUBECONFIG: /kube/config
    env_file:
      - .env
    tty: true
