apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubewatcher.fullname" . }}
  labels:
  {{- include "kubewatcher.labels" . | nindent 4 }}
data:
  handlers.yaml: |-
    handlers:
      {{- toYaml .Values.handlers | nindent 6 }}
  filters.yaml: |-
    filters:
      {{- toYaml .Values.filters | nindent 6 }}
