{{- $fullname := include "kubewatcher.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "kubewatcher.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kubewatcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubewatcher.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubewatcher.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "watch"
            - "-f"
            - "/config/filters.yaml"
            - "-f"
            - "/config/handlers.yaml"
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  key: {{ $key }}
                  name: {{ $fullname }}
          {{- end }}
          volumeMounts:
            - name: filters
              mountPath: /config/filters.yaml
              subPath: filters.yaml
              readOnly: true
            - name: handlers
              mountPath: /config/handlers.yaml
              subPath: handlers.yaml
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: filters
          configMap:
            name: {{ $fullname }}
            items:
              - key: filters.yaml
                path: filters.yaml
        - name: handlers
          configMap:
            name: {{ $fullname }}
            items:
              - key: handlers.yaml
                path: handlers.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
