{{- if .Values.env -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubewatcher.fullname" . }}
  labels:
  {{- include "kubewatcher.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
