# Default values for kubewatcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  filters:
    - kind: Pod
      apiVersion: v1
#    namespaces:
#      include:
#        - surf-screenshotter-dev
#      ignore:
#        - heptio-sonobuoy
      conditions:
        - status.containerStatuses[*].state.terminated.exitCode != 0
      message:
        template: "Pod: {NAME} in {NAMESPACE} terminated with nonzero exit code"
        attributes:
          NAME: metadata.name
          NAMESPACE: metadata.namespace

    - kind: Pod
      apiVersion: v1
      conditions:
        - status.containerStatuses[*].restartCount > 10
      message:
        template: "Pod: {NAME} in {NAMESPACE} has restarted {RESTART_COUNT} times"
        attributes:
          NAME: metadata.name
          NAMESPACE: metadata.namespace
          RESTART_COUNT: status.containerStatuses[*].restartCount

    - kind: Event
      apiVersion: v1
      conditions:
        - type == Warning
#      - reason != ImageGCFailed
#      - reason != FreeDiskSpaceFailed
      message:
        template: "Event: Warning {NAME} in {NAMESPACE} (reason: {REASON}, message: {MESSAGE})"
        attributes:
          NAME: metadata.name
          NAMESPACE: metadata.namespace
          REASON: reason
          MESSAGE: message

    - kind: Job
      apiVersion: batch/v1
      conditions:
        - status.conditions[*].type == Failed
      message:
        template: "Job: {NAME} in {NAMESPACE} failed (reason: {REASON}, message: {MESSAGE})"
        attributes:
          NAME: metadata.name
          NAMESPACE: metadata.namespace
          REASON: status.conditions[*].reason
          MESSAGE: status.conditions[*].message

#  handlers:
#    slack:
#      channel: "${SLACK_HANDLER_CHANNEL}"
#      token: $SLACK_HANDLER_TOKEN
#    telegram:
#      token: $TELEGRAM_HANDLER_API_TOKEN
#      chatId: $TELEGRAM_HANDLER_CHAT_ID

# TODO: For some reason the SLACK_HANDLER_CHANNEL variable won't be interpolated if the value begins with '#'
#  The current solution is simply to list specify the channel without the '#' prefix
#env:
#  SLACK_HANDLER_CHANNEL: "channel"
#  SLACK_HANDLER_TOKEN: "xoxb-blabla..."
#  TELEGRAM_HANDLER_API_TOKEN=1234...
#  TELEGRAM_HANDLER_CHAT_ID=4321...

skipRole: false

image:
  repository: tons/kubewatcher:1.6.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
